#
# Author: Ashwin and Aadarsh
# EECS 4287/5287: Principles of Cloud Computing
#
# Start couchdb 
#
---
#Copy service file from vagrant to Service directory
  - name: Copy service file to VM2
    become: no
    copy:
        src: ~/couchdb_service.yml
        dest: /home/cc/Service/couchdb_service.yml

#Copy service job file from vagrant to Service directory
  - name: Copy job file to VM2
    become: no
    copy:
        src: ~/couchdb_job.yml
        dest: /home/cc/Service/couchdb_job.yml

#Make infile modification for service job file
  - name: Make infile modification for service job file
    ansible.builtin.lineinfile:
        state: present
        path: /home/cc/Service/couchdb_job.yml
        firstmatch: yes
        search_string: 'image: localhost:5000/matinv-server'
        line: '          image: {{ ansible_default_ipv4.address }}:5000/couchdb_image'

#start job with service
  - name: Create the couchdb service
    become: no
    shell: kubectl apply -f /home/cc/Service/couchdb_service.yml

  - name: Start couchdb job
    become: no
    shell: kubectl apply -f /home/cc/Service/couchdb_job.yml


...