#
# Author: Ashwin and Aadarsh
# EECS 4287/5287: Principles of Cloud Computing
#
# Kafka broker 1 service file
#
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-zero-svc
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: kafka-zero-app     # used to match the pod(s) that run the actual matinv server
  ports:
    - name: kafka-zero-port    # not needed, but I have added this
      protocol: TCP     # this is default (so not needed either)
      port: 9092   # the port used by the server inside the pod/container
      targetPort: 9092   # not sure if we need this because if not specified, it is same as port
      nodePort: 30001  # this is what will be externally published
...