#
# Author: Ashwin and Aadarsh
# EECS 4287/5287: Principles of Cloud Computing
#
# Consumer job file
#
---
apiVersion: batch/v1
kind: Job         # We are testing the Job resource type
metadata:
  name: consumer-job  # A name must be given to the Job type in the metadata section
spec:                     # This is the specification where we can even put the number of replicas
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: consumer-app  # this is used in our service yaml file to match with the pod
    spec:                 # actual specification
      containers:
        - name: consumer-zero       # this is going to be used for DNS name
          # Change the IP address to where you are running this
          image: localhost:5000/matinv-server   
          
          imagePullPolicy: Always  # This forces the node to pull the image
          command: ["python3"]
          args: ["consumer.py"]
   #   command: ["kafka_2.13-3.0.0/bin/zookeeper-server-start.sh kafka_2.13-3.0.0/config/zookeeper.properties"]
      restartPolicy: Never  # we ask Kubernetes not to restart

...